# Railway deployment configuration for backend
# This file configures how Railway builds and deploys the Express.js backend

[build]
  builder = "nixpacks"

[deploy]
  startCommand = "cd backend && npm start"
  healthcheckPath = "/health"
  healthcheckTimeout = 300
  restartPolicyType = "on_failure"

[env]
  NODE_ENV = "production"
  PORT = "5000"

